sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2002
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEXcefVCLgdvzdhp6q1
    access-key-secret: lCl6w5YstzKo7QoIlVuVuYPmgkh4iz
    bucket-name: sky-take-out-ygh
  redis:
    host: localhost
    port: 6379
    password: 2002
    database: 0
  wechat:
    appid: wx22792823960fb3c7
    secret: 49eafd87796a510ea8cf9233ae65f05c
